---
CoreSW0:
   hostname: "192.168.137.100"
   port: 22
   platform: ios
   groups:
     - cisco
   data:
     type: coresw
AccesSW1:
   hostname: "192.168.137.101"
   port: 22
   platform: ios
   groups:
     - cisco
   data:
     type: switch
AccesSW2:
   hostname: "192.168.137.102"
   port: 22
   platform: ios
   groups:
     - cisco
   data:
     type: switch
R1:
   hostname: "192.168.137.59"
   port: 22
   platform: ios
   groups:
     - cisco
   data:
     type: router
