# Initialize nornir (InitNornir) with this configuration file
---

inventory:
  plugin: SimpleInventory                   # Inventory plugin to store all the relevant data in three files
  options:
    host_file: "D:/Programs/PyCharm Community/Python PyCharm Projects/NetworkAutomationProject/NornirScripts/ConfigFiles/hosts.yaml"
    group_file: "D:/Programs/PyCharm Community/Python PyCharm Projects/NetworkAutomationProject/NornirScripts/ConfigFiles/groups.yaml"
    defaults_file: "D:/Programs/PyCharm Community/Python PyCharm Projects/NetworkAutomationProject/NornirScripts/ConfigFiles/defaults.yaml"

runner:
  plugin: threaded                         # Nornir script will be run simultaneously over multiple devices
  options:
    num_workers: 10                        # Number of concurrent devices