AccessSW1:
  data:
    type: switch
  groups:
  - cisco
  hostname: 192.168.137.101
  platform:
  - ios
  port: '22'
AccessSW2:
  data:
    type: switch
  groups:
  - cisco
  hostname: 192.168.137.102
  platform:
  - ios
  port: '22'
CoreSW0:
  data:
    type: coresw
  groups:
  - cisco
  hostname: 192.168.137.100
  platform:
  - ios
  port: '22'
R1:
  data:
    type: router
  groups:
  - cisco
  hostname: 192.168.137.156
  platform:
  - ios
  port: '22'
