# File to configure the list of devices with their specific properties
---
CoreSW0:
   hostname: "192.168.137.100"
   port: 22
   platform: ios
   groups:
     - cisco
   data:
     type: coresw
AccessSW1:
   hostname: "192.168.137.101"
   port: 22
   platform: ios
   groups:
     - cisco
   data:
     type: switch
AccessSW2:
   hostname: "192.168.137.102"
   port: 22
   platform: ios
   groups:
     - cisco
   data:
     type: switch
R1:
   hostname: "192.168.137.48"
   port: 22
   platform: ios
   groups:
     - cisco
   data:
     type: router